apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: heapster
    version: v6
    app: heapster
  name: heapster
  namespace: kube-system
spec:
  revisionHistoryLimit: 5
  replicas: 1
  template:
    metadata:
      labels:
        app: heapster
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default.svc
        - --sink=influxdb:http://influxdb.kube-system.svc.cluster.local:8086/
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
      nodeSelector:
        caste: peasant

        

